### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by Offirmo** [WendellAdriel/dev-curriculum#1]
We want a demo !

Could you GitHub pages ?

**Comment by WendellAdriel** [comment]
Hey @Offirmo.

I'm still developing the theme. When I finish I will use it as my GH Page and post the link in this repo as an example.

**Comment by Offirmo** [comment]
:+1: It got featured as this week trending repo ^^

**Comment by WendellAdriel** [comment]
@Offirmo really???? I didn't know that!!!!

**Comment by Offirmo** [comment]
In CSS category http://www.gitly.co/

**Comment by WendellAdriel** [comment]
Really cool!!! Thanks @Offirmo

**Comment by WendellAdriel** [comment]
@Offirmo I finished, you can see the demo here: http://wendelladriel.github.io
