### ISSUE TITLE
I loved your new CV

### ISSUE THREAD

**Issue by edsontrick** [WendellAdriel/dev-curriculum#17]
Could you, please, merge here?

**Comment by klebsoncarneiro** [comment]
Sorry, I didn't get it

Klebson Carneiro


Em ter, 14 de ago de 2018 às 20:40, edsontrick <notifications@github.com>
escreveu:

**Comment by WendellAdriel** [comment]
Sorry @edsontrick, but merge what?

**Comment by edsontrick** [comment]
@WendellAdriel Your new CV -> https://wendelladriel.com/

**Comment by WendellAdriel** [comment]
Oh, I see!!!
I'm still making some tests with it, isn't ready yet to publish as a template.

As soon as I finish it I will create a template using a static site generator!!! :wink:
