### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by WendellAdriel** [WendellAdriel/dev-curriculum#2]
### I need help to create a logo for the project.

I already have something in mind: The logo will be a a icon like this one:
https://www.iconfinder.com/icons/307434/account_contact_male_man_profile_user_vcard_icon#size=128
inside the `<>`

For more details please use this issue or contact me.

**Comment by WendellAdriel** [comment]
I need the file to replace the images in `assets/images` folder and the `screenshot.png`. If you want to help please fork the repo and send a PR with the changes!!! :+1:

**Comment by khaosdoctor** [comment]
On it!

**Comment by WendellAdriel** [comment]
Thanks @khaosdoctor

**Comment by WendellAdriel** [comment]
Can I put it on `in progress` status???

**Comment by khaosdoctor** [comment]
Yes! I'll start tomorrow evening

**Comment by WendellAdriel** [comment]
Thanks a lot @khaosdoctor

**Comment by WendellAdriel** [comment]
@khaosdoctor my wife made a logo to the project!! If you have started yours, send it to me anyways, but if you didn't started yet, there's no problem!! xD

**Comment by khaosdoctor** [comment]
I've finished the logo on friday, I`ll send a PR anyways, if you like it we can use it, otherwise there's no problem xD
